pipeline {
    agent any
    
    tools {
        maven "M3"
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/laurenspruce/lbg-hello-world-maven.git'
            }
        }
        stage('Compile') {
            steps {
                sh "mvn clean compile"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test" // Run tests without skipping compilation
            }
        }
        stage('Package') {
            steps {
                sh "mvn package -Dmaven.test.skip=true" // Skip tests during packaging
            }
        }
    }
}
